### ISSUE TITLE
Contact US

### ISSUE THREAD

**Issue by arpit-bhalla** [SCWD-nitkkr/sponsy-nitkkr.github.io#10]
![image](https://user-images.githubusercontent.com/89131130/145381553-cdc26eb2-1845-45bc-b64e-15fdeefb486a.png)

**Comment by KAHTRAS2009** [comment]
I'm Interested in designing this component.

**Comment by 01manoj10** [comment]
I want to join this

**Comment by arpitBhalla** [comment]
@KAHTRAS2009 @01manoj10 please collaborate

**Comment by HarshSingh-178** [comment]
HarshSingh-178

**Comment by arpitBhalla** [comment]
@HarshSingh-178  @KAHTRAS2009 @01manoj10 Any progress?

**Comment by HarshSingh-178** [comment]
Yes sir we have done the html and css.

**Comment by arpitBhalla** [comment]
Create pull request
