### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by arpit-bhalla** [SCWD-nitkkr/sponsy-nitkkr.github.io#11]
![image](https://user-images.githubusercontent.com/89131130/145381638-307e1241-1d04-4197-a51d-b0d4cefe39f7.png)

**Comment by tanishqsindhu** [comment]
I'm Interested in designing this component.

**Comment by abhii30** [comment]
I'm interested

**Comment by bhavyajain8** [comment]
I'm interested
