### ISSUE TITLE
NavBar

### ISSUE THREAD

**Issue by arpit-bhalla** [SCWD-nitkkr/sponsy-nitkkr.github.io#3]
![image](https://user-images.githubusercontent.com/89131130/145380998-256a38eb-e17a-49a1-92d4-b69f62ea2419.png)

**Comment by Khiyaram3** [comment]
Khiyaram3 navbar

**Comment by navanish07** [comment]
navanish07

**Comment by arpitBhalla** [comment]
@navanish07 @Khiyaram3 please collaborate

**Comment by Khiyaram3** [comment]
Sir Navbar to bana diya lekin use add kaise karu isme ya direct code paste
karna hia

**Comment by HarshKumar2221** [comment]
I'm interested in designing this component
