### ISSUE TITLE
Hero Section

### ISSUE THREAD

**Issue by arpit-bhalla** [SCWD-nitkkr/sponsy-nitkkr.github.io#4]
![image](https://user-images.githubusercontent.com/89131130/145381043-390ea6a4-a8ae-4d74-90b3-c87dd6a069e6.png)

**Comment by Raghav0407** [comment]
Hello, Raghav here.
I want to  be a part of the **HERO SECTION**..

**Comment by Akv00** [comment]
Hii, Abhishek here.
