### ISSUE TITLE
About Us

### ISSUE THREAD

**Issue by arpit-bhalla** [SCWD-nitkkr/sponsy-nitkkr.github.io#6]
![image](https://user-images.githubusercontent.com/89131130/145381171-b244fca5-026e-4b46-8902-8615ae13bc96.png)

**Comment by KarGitH** [comment]
I want to be a part of this.

**Comment by bhawarth-garg** [comment]
bhawarth-garg

**Comment by KarGitH** [comment]
sir plz tell how can i submit the work
