### ISSUE TITLE
Latest News

### ISSUE THREAD

**Issue by arpit-bhalla** [SCWD-nitkkr/sponsy-nitkkr.github.io#9]
![image](https://user-images.githubusercontent.com/89131130/145381483-a17076cb-422b-4f37-b99f-d6f02576fb11.png)

**Comment by shubhraj661** [comment]
I'm Interested in designing this component.

**Comment by Quantsvarun** [comment]
i'm interested in designing this component

**Comment by arpitBhalla** [comment]
@beRlin4662 Please collaborate with @Quantsvarun

**Comment by AditiYdv28** [comment]
I am interested in designing this component
